config/routes.rb
LivingLeast::Application.routes.draw do
  get "splash/index"

  devise_for :users

  resources :communications

  resources :purchases

  
  match '/purchases/hook' => 'purchases#hook', :via => [:post]

  root :to => 'splash#index'

end

app/models/communication.rb
class Communication < ActiveRecord::Base
  attr_accessible :message, :purchase_id, :to_id, :user_id
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
	belongs_to :user
  attr_accessible :amount, :category, :city, :merchant_name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :purchases
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/communications_controller.rb
class CommunicationsController < ApplicationController
  # GET /communications
  # GET /communications.json
  def index
    @communications = Communication.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @communications }
    end
  end

  # GET /communications/1
  # GET /communications/1.json
  def show
    @communication = Communication.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @communication }
    end
  end

  # GET /communications/new
  # GET /communications/new.json
  def new
    @communication = Communication.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @communication }
    end
  end

  # GET /communications/1/edit
  def edit
    @communication = Communication.find(params[:id])
  end

  # POST /communications
  # POST /communications.json
  def create
    @communication = Communication.new(params[:communication])

    respond_to do |format|
      if @communication.save
        format.html { redirect_to @communication, notice: 'Communication was successfully created.' }
        format.json { render json: @communication, status: :created, location: @communication }
      else
        format.html { render action: "new" }
        format.json { render json: @communication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /communications/1
  # PUT /communications/1.json
  def update
    @communication = Communication.find(params[:id])

    respond_to do |format|
      if @communication.update_attributes(params[:communication])
        format.html { redirect_to @communication, notice: 'Communication was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @communication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communications/1
  # DELETE /communications/1.json
  def destroy
    @communication = Communication.find(params[:id])
    @communication.destroy

    respond_to do |format|
      format.html { redirect_to communications_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/purchases_controller.rb
require 'Fetcher'


class PurchasesController < ApplicationController
  # GET /purchases
  # GET /purchases.json
  def index
    @purchases = Purchase.all.reverse
    @user_purchases = current_user.purchases

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @purchases }
    end
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
    @purchase = Purchase.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @purchase }
    end
  end

  # GET /purchases/new
  # GET /purchases/new.json
  def new
    @purchase = Purchase.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @purchase }
    end
  end

  # GET /purchases/1/edit
  def edit
    @purchase = Purchase.find(params[:id])
  end

  # POST /purchases
  # POST /purchases.json
  def create
    @purchase = Purchase.new(params[:purchase])
    @purchase.user_id = current_user.id

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to @purchase, notice: 'Purchase was successfully created.' }
        format.json { render json: @purchase, status: :created, location: @purchase }
      else
        format.html { render action: "new" }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  def hook
    message_data = params[:message_data]
    account_id = params[:account_id]
    unless message_data.nil?
      message_id = message_data[:message_id]
      unless message_id.nil? || account_id.nil?
        fetcher = Fetcher.new(account_id, message_id)
        matched = fetcher.fetch
        unless matched.nil?

          purchase = Purchase.new
          purchase.merchant_name = matched.merchant
          purchase.category = matched.category
          purchase.city = matched.location
          purchase.amount = matched.amount

          if purchase.save
            render :json => { :result => "ok", :purchase => matched }.as_json, :status => 202
          else
            render :json => { :result => "failed to save", :purchase => matched }.as_json, :status => 503
          end
        else
          render :json => { :result => "no purchases found" }.as_json, :status => 204
        end
      else
        render :json => { :result => "fail", :message => "missing message_id"}.as_json, :status => 422
      end
    else
      render :json => { :result => "fail", :message => "missing message_data"}.as_json, :status => 422
    end
  end

  # PUT /purchases/1
  # PUT /purchases/1.json
  def update
    @purchase = Purchase.find(params[:id])

    respond_to do |format|
      if @purchase.update_attributes(params[:purchase])
        format.html { redirect_to @purchase, notice: 'Purchase was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    @purchase = Purchase.find(params[:id])
    @purchase.destroy

    respond_to do |format|
      format.html { redirect_to purchases_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index
  	if user_signed_in?
  		redirect_to :purchases
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/communications_helper.rb
module CommunicationsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/communications/_form.html.erb
<%= form_for(@communication) do |f| %>
  <% if @communication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@communication.errors.count, "error") %> prohibited this communication from being saved:</h2>

      <ul>
      <% @communication.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :to_id %><br />
    <%= f.number_field :to_id %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :purchase_id %><br />
    <%= f.number_field :purchase_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/communications/edit.html.erb
<h1>Editing communication</h1>

<%= render 'form' %>

<%= link_to 'Show', @communication %> |
<%= link_to 'Back', communications_path %>

app/views/communications/index.html.erb
<h1>Listing communications</h1>

<table>
  <tr>
    <th>User</th>
    <th>To</th>
    <th>Message</th>
    <th>Purchase</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @communications.each do |communication| %>
  <tr>
    <td><%= communication.user_id %></td>
    <td><%= communication.to_id %></td>
    <td><%= communication.message %></td>
    <td><%= communication.purchase_id %></td>
    <td><%= link_to 'Show', communication %></td>
    <td><%= link_to 'Edit', edit_communication_path(communication) %></td>
    <td><%= link_to 'Destroy', communication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Communication', new_communication_path %>

app/views/communications/new.html.erb
<h1>New communication</h1>

<%= render 'form' %>

<%= link_to 'Back', communications_path %>

app/views/communications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @communication.user_id %>
</p>

<p>
  <b>To:</b>
  <%= @communication.to_id %>
</p>

<p>
  <b>Message:</b>
  <%= @communication.message %>
</p>

<p>
  <b>Purchase:</b>
  <%= @communication.purchase_id %>
</p>


<%= link_to 'Edit', edit_communication_path(@communication) %> |
<%= link_to 'Back', communications_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Living Least</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
  	<!--  Header ================================== -->
  	<header>
      <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container">
            <a class="brand" href="/">Living Least</a>
            <div class="nav-collapse collapse">
              <p class="navbar-text pull-right">
                <% if user_signed_in? %>
                  <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, class: "btn btn-small"  %>
                <% else %>
                  <%= link_to "Sign In", new_user_session_path, class: "btn btn-small" %> 
                <% end %> 
              </p>
            </div><!--/.nav-collapse -->
          </div>
        </div>
      </div>
  	</header>
		
		<div class="pulldown">
    	<%= yield %>
  	</div>

    <footer>
    	<p>LivingLeast. Made in San Francisco.</p>
    </footer>
  </div>
</body>

<%= yield :scripts %>

</html>

app/views/purchases/_form.html.erb
<%= form_for(@purchase) do |f| %>
  <% if @purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
      <% @purchase.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :merchant_name %><br />
    <%= f.text_field :merchant_name %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/purchases/edit.html.erb
<h1>Editing purchase</h1>

<%= render 'form' %>

<%= link_to 'Show', @purchase %> |
<%= link_to 'Back', purchases_path %>

app/views/purchases/index.html.erb
<div>
	<h2>Your Purchases<h2>
		<% @user_purchases.each do |purchase| %>
	    <div>
	      <h4 style="color: #347AC9">
	      	<%= purchase.merchant_name%> 
	      </h4> 
	      <p>
	        <%= purchase.city %> | 
	        $<%= purchase.amount %> | 
	        <%= purchase.category %>
	      </p>
   		</div>
   	<% end %>
	<hr>


	<h2>Other's Purchases<h2>		
		<% @purchases.each do |purchase| %>
	    <div>
	      <h4 style="color: #347AC9">
	      	<%= purchase.merchant_name%> 
	      </h4> 
	      <p>
	        <%= purchase.city %> | 
	        $<%= purchase.amount %> | 
	        <%= purchase.category %>
	      </p>
   		</div>
   	<% end %>
</div>

app/views/purchases/new.html.erb
<h1>New purchase</h1>

<%= render 'form' %>

<%= link_to 'Back', purchases_path %>

app/views/splash/index.html.erb
<div class="homeimage">
  <%= image_tag("livingleastlogoblk.png") %> <br>
  <h2>Win by spending less than your friends</h2> <br>
  <%= link_to "Sign Up To Play!", new_user_registration_path, class: "btn btn-success btn-large"  %>
</div>